config/routes.rb
Rails.application.routes.draw do
  root 'prjcts#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :prjcts, path: 'projects', except: [:index] do
  	resources :pictures, except: [:show, :index]
  	resources :comments
  	member do 
  		get 'like'
  		get 'unlike'
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :prjct

  validates :user_id, presence: true  
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :prjct
  validates :prjct, :presence => true
  mount_uploader :image, ImageUploader
end

app/models/prjct.rb
class Prjct < ApplicationRecord
	acts_as_votable

	has_many :pictures, dependent: :destroy
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
	acts_as_voter
	has_many :comments

	class << self
		def from_omniauth(auth_hash)
			user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
			user.name = auth_hash['info']['name']
			user.image_url = auth_hash['info']['image']
			user.url = auth_hash['info']['urls'][user.provider.capitalize]
			user.save!
			user
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
  	@current_user ||= User.find_by(id: session[:user_id])
  end

  def admin_user
  	@admin_user ||= current_user.uid == Rails.application.secrets.admin_uid
  end

  helper_method :current_user

  helper_method :admin_user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_prjct

	def create
		@comment = @prjct.comments.build(comment_params)
		@comment.user = current_user
		if @comment.save
			respond_to do |format|
				format.html { redirect_to root_path }
				format.js
			end
		end
		
	end

	def destroy
		@comment = @prjct.comments.find(params[:id])

		if @comment.user == current_user
			@comment.delete
			respond_to do |format|
				format.html { redirect_to root_path }
				format.js
			end
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

	def set_prjct
		@prjct = Prjct.find(params[:prjct_id])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	before_action :set_picture, only: [:show, :edit, :update, :destroy]
	before_action :set_prjct

	def new
		@picture = Picture.new
	end

	def create
		@picture = Picture.new(picture_params)
		@picture.prjct_id = @prjct.id

		if @picture.save
			redirect_to @prjct
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @picture.update(picture_params)
			redirect_to @prjct
		else
			render 'new'
		end
	end

	def destroy
		@picture.destroy
		redirect_to prjct_path(@prjct)
	end

	private
		def set_picture
			@picture = Picture.find(params[:id])
		end

		def set_prjct
			@prjct = Prjct.find(params[:prjct_id])
		end

		def picture_params
			params.require(:picture).permit(:image, :caption)
		end


end

app/controllers/prjcts_controller.rb
class PrjctsController < ApplicationController

	before_action :set_prjct, only: [:show, :edit, :update, :destroy, :like, :unlike]

	def index
		@prjcts = Prjct.all.order("created_at desc")
	end

	def show
		@pictures = Picture.where(prjct_id: @prjct.id).order("created_at DESC")
		@prjct = Prjct.find(params[:id])
	end

	def new
		@prjct = Prjct.new
	end

	def create
		@prjct = Prjct.new(prjct_params)
		if @prjct.save
			redirect_to @prjct, notice: 'Project created.'
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @prjct.update(prjct_params)
			redirect_to @prjct, notice: 'Project updated.'
		else
			render :edit
		end
	end

	def destroy
		@prjct.destroy
		redirect_to root_path, notice: 'Project entry was deleted.'
	end

	def like
		if @prjct.liked_by current_user
			respond_to do |format|
				format.html { redirect_to :back }
				format.js
			end
		end
	end

	def unlike
		if @prjct.unliked_by current_user
			respond_to do |format|
				format.html { redirect_to :back }
				format.js
			end
		end
	end

	private
		def set_prjct
			@prjct = Prjct.find(params[:id])
		end

		def prjct_params
			params.require(:prjct).permit(:title, :description, :deight)
		end
	end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		begin
		    @user = User.from_omniauth(request.env['omniauth.auth'])
		    session[:user_id] = @user.id
		    flash[:success] = "Welcome, #{@user.name}!"
  		rescue
    		flash[:warning] = "There was an error while trying to authenticate you..."
  		end
  		redirect_to root_path
	end

	def destroy
		if current_user
			session.delete(:user_id)
			flash[:success] = 'Peace'
		end
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def logo(name)
		file_path = "#{Rails.root}/app/assets/images/#{name}.svg"
		return File.read(file_path).html_safe if File.exists?(file_path)
		'(not found)'
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nav_helper.rb
module NavHelper
	def new_project_link
		link_to 'New Project', new_prjct_path, class: 'btn-new'
	end

	def add_picture_link
		link_to 'New Picture', new_prjct_picture_path(@prjct), class: 'btn-new'
	end

	def edit_project_link
		link_to 'Edit Project', edit_prjct_path, class: 'btn-new'
	end

	def delete_project_link
		link_to 'Delete This', @prjct, method: :delete, class: 'btn-new', data: { confirm: 'Are You Sure?' }
	end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/prjcts_helper.rb
module PrjctsHelper
	def display_likes(prjct)
		votes = prjct.votes_for.up.by_type('User')
		return count_likers(votes)
	end

	def liked_prjct(prjct)
		return 'glyphicon-heart' if current_user.voted_for? prjct
		'glyphicon-heart-empty'
	end

	private

	def count_likers(votes)
		vote_count = votes.size
		vote_count.to_s
	end
end

app/views/comments/_comment.html.erb
	<div class="comment-space">
		<div class="user-name">
			<%= comment.user.name %>
		</div>
		<div class="comment-content">
			<%= comment.content %>
		</div>
		<% if comment.user == current_user %>
			<%= link_to prjct_comment_path(@prjct, comment), method: :delete, data: { confirm: "sure?" }, remote: true do %>
				<span class="glyphicon glyphicon-trash delete-comment"></span>
			<% end %>

		<% end %>
	</div>

app/views/comments/_form.html.erb
<div class="container comment-form-container">
	<div class="comment-form">
		<%= form_for([@prjct, @prjct.comments.build], remote: true) do |f| %>
			<%= f.text_field :content, placeholder: 'Drop a comment', class: 'comment_content form-control', id: "comment_content_#{@prjct.id}" %>
		<% end %>
	</div>
</div>

app/views/comments/create.js.erb
$('#comments_<%= @prjct.id %>').prepend("<%=j render 'comments/comment', prjct: @prjct, comment: @comment %>");
$('#comment_content_<%= @prjct.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @prjct.id %>').html("<%= j render @prjct.comments, prjct: @prjct, comment: @comment %>");

app/views/layouts/_nav.html.erb
<div class="nav-drawer">
<% if current_user && admin_user %>
		<%= yield :menu %>
	<hr/>
<% end %>


<ul>
	<li><%= link_to 'Home', root_path %></li>
</ul>

<% if current_user %>
	<ul class="logout">
		<li><hr/></li>
		<li><%= current_user.name %></li>
		<li><%= link_to 'Logout', logout_path, method: :delete %></li>
	</ul>
<% else %>
	<ul class="login">
		<li><hr/></li>
		<li><%= link_to '/auth/facebook' do %>
				Login <i class="fa fa-facebook-official" aria-hidden="true"></i>
			<% end %>
		</li>
	</ul>
<% end %>


</div>

<button class="hamburger hamburger--stand menu-trigger" type="button">
  <span class="hamburger-box">
    <span class="hamburger-inner"></span>
  </span>
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zadé Moore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/nav'%>
  	<div class="rapper">
    	<%= yield %>
    </div>
    <div class="logo">
    	<% if controller.controller_name == "prjcts" && controller.action_name == "show" %>
    		<%= render partial: 'prjcts/likes', locals: {prjct: @prjct} %>
	    	<% if current_user %>
			    <div class="like-button">
			  		<% if current_user.liked? @prjct %>
  						<%= link_to '', unlike_prjct_path(@prjct.id), remote: true,
                        id: "like_#{@prjct.id}",
                        class: "glyphicon glyphicon-heart" %>
					<% else %>
  						<%= link_to '', like_prjct_path(@prjct.id), remote: true,
                        id: "like_#{@prjct.id}",
                        class: "glyphicon glyphicon-heart-empty" %>
					<% end %>
			  	</div>
			<% else %>
			    	<span class="glyphicon glyphicon-heart-empty like"></span>
			<% end %>
		<% end %>
	    <%= logo'Zadé-00' %>
    </div>
  </body>

	<script>
	  // Look for .hamburger
	  var hamburger = document.querySelector(".hamburger");
	  var trigger = document.querySelector(".menu-trigger");
	  var drawer = document.querySelector(".nav-drawer");
	  var rapper = document.querySelector(".rapper")
	  // On click
	  hamburger.addEventListener("click", function() {
	    // Toggle class "is-active"
	    hamburger.classList.toggle("is-active");
	    trigger.classList.toggle("active");
	    drawer.classList.toggle("open");
	    rapper.classList.toggle("over");
	    // Do something else, like open/close menu
	  });
	</script>
</html>

app/views/pictures/_form.html.erb
<%= form_for([@prjct, picture]) do |f| %>
 <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :caption %>
    <%= f.text_area :caption, class: 'form-control fixed-text' %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/pictures/edit.html.erb
<section class="top">
	<h1>Edit</h1>
</section>
<section>
	<%= form_for([@prjct, @picture]) do |f| %>
		<div class="edit-form-img">
			<%= image_tag @picture.image.url %>
		</div>
		<div class="edit-picture-form">
	  		<div class="form-group">
	    		<%= f.label :caption %>
	    		<%= f.text_area :caption, class: 'form-control fixed-text' %>
	  		</div>

	  		<div class="actions">
	    		<%= f.submit %>
	  		</div>
	  	</div>

	<% end %>
</section>	

app/views/pictures/new.html.erb
<section class="top">	
	<h1>New Picture</h1>
</section>
<section>

	<%= render 'form', picture: @picture %>

</section>

<%= link_to 'Back', @prjct %>

app/views/prjcts/_form.html.erb
<%= form_for(prjct) do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, class: 'form-control fixed-text' %>
	</div>

	<div class="form-group">
		<%= f.label 'date' %>
		<%= f.date_field :deight, class: 'form-control' %>
	</div>

	<div class="actions">
    	<%= f.submit 'Create Project', class: 'btn-new' %>
  	</div>
<% end %>

app/views/prjcts/_likes.html.erb
<div class="likes" id="likes_<%= @prjct.id %>">
	<%= display_likes @prjct %>
</div>

app/views/prjcts/edit.html.erb
<section class="top">
	<h1>Edit</h1>
</section>
<section>
	<% if current_user && admin_user %>
		<%= render 'form', prjct: @prjct %>
	<% else %>
		<%= link_to 'auth/facebook' do %>
			Admin Only <i class="fa fa-facebook-official" aria-hidden="true"></i>
		<% end %>
	<% end %>
</section>	

app/views/prjcts/index.html.erb
<% content_for :menu do %>
	<%= new_project_link %>
<% end %>

<section class="top">
	<h1>projects</h1>
</section>
<section class="container">
	<% @prjcts.each do |prjct| %>
		<div class="projects">
			<%= link_to prjct do %>
				<% if prjct.pictures.exists? %>
					<div class="project with" style="background-image: linear-gradient(to bottom, rgba(255, 255, 255, 0.2), rgba(255, 255, 255, 0.2)), url('<%= prjct.pictures.last.image.url %>');">
						<h3><%= prjct.title %></h3>
					</div>
				<% else %> 
					<div class="project">
						<h3><%= prjct.title %></h3>
						<p> image coming soon ;) </p>
					</div>
				<% end %>
			<% end %>
			<% if current_user && admin_user %>
				<div class="action-links">
					<%= link_to 'Add Picture', new_prjct_picture_path(prjct), class: 'btn btn-new' %>
					<%= link_to 'Edit', edit_prjct_path(prjct), class: 'btn btn-new' %>
					<%= link_to 'Delete', prjct, method: :delete, data: { confirm: 'Delete this project?' }, class: 'btn btn-new' %>
				</div>
			<% end %>
		</div>
	<% end %>
</section>

app/views/prjcts/like.js.erb
$("#like_<%= @prjct.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#like_<%= @prjct.id %>").attr("href", '/prjcts/<%= @prjct.id %>/unlike');
$("#likes_<%= @prjct.id %>").html("<%= j (render partial:'prjcts/likes', locals: { prjct: @prjct } ) %>");

app/views/prjcts/new.html.erb
<section class="top">
	<h1> new </h1>
</section>
<section>
	<% if current_user && admin_user %>
		<%= render 'form', prjct: @prjct %>
	<% else %>
		<%= link_to '/auth/facebook' do %>
			Admin Only <i class="fa fa-facebook-official" aria-hidden="true"></i>
		<% end %>
	<% end %>
</section>

app/views/prjcts/show.html.erb
<% content_for :menu do %>
	<ul class="actions">
		<li><%= add_picture_link %></li>
		<li><%= edit_project_link %></li>
		<li><%= delete_project_link %></li>
	</ul>
<% end %>
<p id="notice"><%= notice %></p>

<section class="overview">
	<h2><%= @prjct.title %></h2>

	<p>
	  <%= @prjct.description %>
	</p>

</section>
<% if @pictures.blank? %>
<section class="nopics">
	<p>Pictures coming soon</p>
	<% if current_user && admin_user %>
		<%= link_to 'Add Picture', new_prjct_picture_path(@prjct), class: 'btn btn-new' %>
	<% end %>
</section>
<% else %>
	<% @pictures.each do |picture| %>
	<section class="images">
		<div class="thousandwords">
			<%= image_tag picture.image.url %>
			<div class="<%= cycle("left", "right") %>">
				<%= picture.caption %>
				<% if current_user && admin_user %>
					<ul>
						<li>
							<%= link_to 'Edit Caption', edit_prjct_picture_path(@prjct, picture), class: 'btn btn-new' %>
						</li>
						<li>
							<%= link_to 'Delete Image', [@prjct, picture], method: :delete, class: 'btn btn-new' %>
						</li>
					</ul>
				<% end %>
			</div>
		</div>
	</section>
	<% end %>
<% end %>
<section class="comments">
	<div class="comments" id="comments_<%= @prjct.id %>">
		<% if @prjct.comments %>
		 	<%= render @prjct.comments.order('created_at DESC'), prjct: @prjct %>
		<% end %>
	</div>
	<% if current_user %>
		<%= render 'comments/form' %>
	<% end %>
	 
		
</section>